#!/bin/bash
#SBATCH -N 1
#SBATCH -c 64
#SBATCH -J hw2-openmp
#SBATCH -t 00:30:00
#SBATCH -o ./slurm_outs/slurm_%j.out

# Define a grid of n values for which the application will be run
n_values=(10000 20000 40000 80000 160000 320000)
c=64
bs=6

# Set OpenMP environment variables
export OMP_NUM_THREADS=$c       # Set the number of threads to 32
export OMP_PLACES=cores         # Bind threads to cores for potentially better performance

# filename
filename="omp.csv"

rm -f $filename
echo "n, bs, time, c" >> $filename

# Loop over each n value
for n in "${n_values[@]}"
do
    # Run the application with the current n value
    # output=$(srun -n 1 ./build/openmp -n $n -s 1 -bs $bs) # to run on slurm
    output=$(./build/openmp -n $n -s 1 -bs $bs) 
    
    # Extract the simulation time from the output
    sim_time=$(echo $output | awk -F' = ' '{print $2}' | awk '{print $1}')     
    # Annotate the s value, n value and simulation time on the same line
    echo "$n, $bs, $sim_time, $c" >> $filename
done